version: "3.9"

services:
  backend:
    image: jobportal-backend  # Use locally built backend image
    ports:
      - "4000:4000"  # Expose backend on port 4000
    networks:
      - mern
    environment:
      MONGO_URI: mongodb://mongodb:27017/mydatabase
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - mongodb

  frontend:
    image: jobportal-frontend  # Use locally built frontend image
    ports:
      - "5173:5173"  # Expose frontend on port 5173
    networks:
      - mern
    environment:
      REACT_APP_API_URL: http://backend:4000

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
